---
title: "Supplementary Figures for Thesis Proposal"
author: "Linnea Rock"
date:
output: html_document
---

```{r setup, include=FALSE}
library(patchwork)
library(tidyverse)
library(readxl)
library(lubridate)
library(dataRetrieval)
getwd()

##CONDUCTIVITY DATA####
#function to convert actual conductivity to specific conductivity 
SC <- function(AC, t) {
  AC / (1 - (25 - t) * .019)
}

# Example of how to read in data from different standardized files using a function 
readSP <- function(files) {
  logger <- read.csv(files[1]) # read in first file
  
  for(i in 1:length(files)){ # if there are more than one file, rbind files 
    logger <- rbind(logger,read.csv(files[i]))
  }
  
  logger =  logger %>% 
    drop_na() %>%
    select(Date, Low.Range, Full.Range, Temp) %>%
    mutate(char = as.character(Date),
           date = as.POSIXct(char, format = "%m-%d-%Y %H:%M:%S", tz = "America/Chicago")) %>%
    select(date, Low.Range, Full.Range, Temp) %>%
    mutate(sp.cond = SC(Full.Range, Temp))
  
  return(logger)
}

##ME###
loggerME_Epi <- readSP(c("Data/HOBO_Loggers/MENDOTA/SURFACE_2019-20/20758346.csv")) %>%
  filter(date < "2020-04-01 9:45:00 ")

loggerME_Hypo <- readSP(c("Data/HOBO_Loggers/MENDOTA/BOTTOM_2019-20/20758341.csv"))%>%
  filter(date < "2020-04-01 9:45:00 ")

##YN###
loggerYN = readSP(c("Data/HOBO_Loggers/YN/Dec19_Feb4/20758343_YN.csv", "Data/HOBO_Loggers/YN/Feb4_Mar16/20758343_YN.csv"))

##YI###
loggerYI <- readSP(c("Data/HOBO_Loggers/YI/Dec19_Feb4/20758347_YI.csv", "Data/HOBO_Loggers/YI/Feb4_Mar16/20758347_YI.csv")) %>%
  filter(date != "2020-02-04 14:30:00")

##YS### 
#Loading in data from conductivity loggers:
loggerYS = readSP(c("Data/HOBO_Loggers/YS/Dec19_Feb3/20758348_YS.csv","Data/HOBO_Loggers/YS/Feb3_Mar16/20758348_YS.csv")) %>% 
  filter(date != "2020-03-16 08:30:00") #getting rid of data that were collected while logger was out of the water

##SW###
loggerSW <- readSP(c("Data/HOBO_Loggers/SW/Dec19_Feb3/20378151_SW.csv", "Data/HOBO_Loggers/SW/Feb3_Mar16/20378151_SW.csv"))

##6MC###
#Loading in data from conductivity loggers:
fileNames = c("Data/HOBO_Loggers/6MC/Dec19_Feb4/20758342_6MC.csv", "Data/HOBO_Loggers/6MC/Feb4_Mar16/20758342_6MC.csv")
logger6MC = readSP(fileNames)  %>%
  filter(date != "2020-03-16 10:00:00")

##DC###
loggerDC <- readSP(c("Data/HOBO_Loggers/DC/Dec19_Feb4/20758338_DC.csv", "Data/HOBO_Loggers/DC/Feb4_Mar16/20758338_DC.csv"))

##PBMS###
loggerPBMS <- readSP(c("Data/HOBO_Loggers/PBMS/Dec19_Feb3/20758344_PBMS.csv", "Data/HOBO_Loggers/PBMS/Feb3_Mar16/20758344_PBMS.csv"))

##PBSF###
loggerPBSF <- readSP(c("Data/HOBO_Loggers/PBSF/Jan2_Jan15/20758339_PBSF.csv","Data/HOBO_Loggers/PBSF/Jan21_Feb4/20758339_PBSF.csv", "Data/HOBO_Loggers/PBSF/Feb4_Mar16/20758339_PBSF.csv" ))



##CHLORIDE DATA####
#function to read in data for chloride
readCL <- function(X) {
  lab <- read_xlsx("Data/chloride_lab.xlsx", sheet = X) %>%
    mutate(date = as.POSIXct(datetime_collected, format = "%m-%d-%Y %h:%m:%s", tz = "America/Chicago")) %>%
    mutate(date = round_date(datetime_collected, "30 minutes"))
}

labYN <- readCL("YN")
labYI <- readCL("YI")
labYS <- readCL("YS")
labSW <- readCL("SW")
lab6MC <- readCL("6MC")
labDC <- readCL("DC")
labPBMS <- readCL("PBMS")
labPBSF <- readCL("PBSF")




##DISCHARGE DATA ####
format <- function(d) {
  d %>%
  rename(discharge = X_00060_00000) %>%
  select(dateTime, discharge) %>%
  mutate(discharge = discharge * 0.028316847) %>%
  rename(date = dateTime)
}

d.YN <- readNWISuv("05427850", "00060", "2019-01-01", "", tz = "America/Chicago") %>%
  format()
d.YI <- readNWISuv("05428500", "00060", "2019-01-01", "", tz = "America/Chicago") %>%
  format()
d.6MC <- readNWISuv("05427910", "00060", "2019-01-01", "", tz = "America/Chicago") %>%
  format()
d.DC <- readNWISuv("05427930", "00060", "2019-01-01", "", tz = "America/Chicago") %>%
  format()
d.PBMS <- readNWISuv("05427948", "00060", "2019-01-01", "", tz = "America/Chicago") %>%
  format()
d.PBSF <- readNWISuv("054279465", "00060", "2019-01-01", "", tz = "America/Chicago") %>%
  format()



#Function for linear regression of specific conductance vs. chloride
cl.cond.plot <- function(df1, df2, X) {
  d <- df1 %>%
    left_join(df2, by = "date")
  
  ggplot(d, aes(chloride_mgL, sp.cond)) +
    geom_point() + 
    geom_smooth(method = "lm", se = FALSE, color = "#7496D2") +
    labs(y = "Specific Conductivity (µS/cm) @ 25°C\n", 
         x = "\nChloride Concentration (mg/L)") +
    theme(panel.background = element_rect(fill = "white", colour = "white",
                                          size = 2, linetype = "solid"),
          panel.grid.major = element_line(size = 0.25, linetype = 'solid',
                                          colour = "gray88"), 
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                          colour = "gray88"),
          axis.text = element_text(size =13, face = "bold"),
          axis.title = element_text(size =13, face = "bold"))
}

#function to quickly add captions
capt <- function(X) {
  plot_annotation(caption = paste(strwrap(X), collapse = "\n"))
}

#figurs with captions 
YN <- cl.cond.plot(loggerYN, labYN, "YN") +
  capt("Specific conductivity vs. chloride relationship in the Yahara River at Highway 113. (inlet to Lake Mendota). The linear regression is represented by the equation y=8.6x+360. The positive correlation (r = 0.81) has an r-squared value of 0.66, and a p-value of 0.094.")

YI <- cl.cond.plot(loggerYI, labYI, "YI")+ 
  capt("Specific conductivity vs. chloride relationship in the Yahara River at E. Main St. (outlet of Lake Mendota and inlet of Lake Monona). The linear regression is represented by the equation y=3.8x+360. The positive correlation (r = 0.64) has an r2 value of 0.41 and a p-value of 0.25.")

YS <- cl.cond.plot(loggerYS, labYS, "YS")+
  capt("Specific conductivity vs. chloride relationship in the Yahara River at Broadway St. (oulet of Lake Monona). The linear regression is represented by the equation y=22x-830. The positive correlation (r = 0.91) has an r2 value of 0.83, and a p-value of 0.033.")

SW <- cl.cond.plot(loggerSW, labSW, "SW")+
  capt("Specific conductivity vs. chloride relationship in the Starkweather Creek at Olbrich Garden (inlet of Lake Monona). The linear regression is represented by the equation y=3.7x+530. The positive correlation (r = 0.87) has an r2 value of 0.76, and a p-value of 0.58")

SMC <- cl.cond.plot(logger6MC, lab6MC, "6MC") +
  capt("Specific conductivity vs. chloride relationship in the Sixmile Creek at Highway M. (inlet to Lake Mendota). The linear regression is represented by the equation y=18x+18. The positive correlation (r = 0.94) has an r2 value of 0.88, and a p-value of 0.018.")

DC <- cl.cond.plot(loggerDC, labDC, "DC") +
  capt("Specific conductivity vs. chloride relationship in the Dorn Creek at Highway M. (inlet to Lake Mendota). The linear regression is represented by the equation y=-5.9x+1100. The negative correlation (r = -0.81) has an r2 value of 0.66, and a p-value of 0.094.")

PBMS <- cl.cond.plot(loggerPBMS, labPBMS, "PBMS")+
  capt("Specific conductivity vs. chloride relationship in the Main Stem of Pheasant Branch Creek (inlet to Lake Mendota). The linear regression is represented by the equation y=5.2x+450. The positive correlation (r = 0.78) has an r2 value of 0.61, and a p-value of 0.12.")

a <- loggerPBSF %>%
mutate(date = round_date(date, "30 minutes")) 

PBSF <-cl.cond.plot(a, labPBSF, "PBSF")+
  capt("Specific conductivity vs. chloride relationship in the South Fork of Pheasant Branch (high chloride contribution to Lake Mendota). The linear regression is represented by the equation y=2.6x+320. The positive correlation (r = 1) has an r2 value of 1, and a p-value of 0.058.")



#function to create QC figures 
q.cl <- function(dfx, dfy, X) {
  qsc <- dfx %>%
    left_join(dfy, by = "date")
  
  ggplot(qsc, aes(discharge, chloride_mgL)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "#7496D2") +
    labs(y = "Chloride Concentration (mg/L)\n", 
         x = "\nDischarge (m^3/S)") +
    theme(panel.background = element_rect(fill = "white", colour = "white",
                                          size = 2, linetype = "solid"),
          panel.grid.major = element_line(size = 0.25, linetype = 'solid',
                                          colour = "gray88"), 
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                          colour = "gray88"),
          axis.text = element_text(size =13, face = "bold"),
          axis.title = element_text(size =13, face = "bold"))  
}

#figures with captions
QYN <- q.cl(labYN, d.YN, "YN_cl")+
  capt("Q-C relationship in the Yahara River at Highway 113. (inlet to Lake Mendota). The linear regression is represented by the equation y=-4.2x+67. The negative correlation (r = -0.76) has an r2 value of 0.58, and a p-value of 0.14.")


QYI <- q.cl(labYI, d.YI, "YI_cl") +
  capt("Q-C relationship in the Yahara River at E. Main St. (outlet of Lake Mendota and inlet of Lake Monona). The linear regression is represented by the equation y=0.3x+51. The positive correlation (r = 0.55) has an r2 value of 0.30 and a p-value of 0.26.")

Q6MC <- q.cl(lab6MC, d.6MC, "6MC_cl") +
  capt("Q-C relationship in the Sixmile Creek at Highway M. (inlet to Lake Mendota). The linear regression is represented by the equation y=-12x+59. The negative correlation (r = -0.92) has an r2 value of 0.90, and a p-value of 0.01.")

QDC <- q.cl(labDC, d.DC, "DC_cl") +
  capt("Q-C relationship in the Dorn Creek at Highway M. (inlet to Lake Mendota). The linear regression is represented by the equation y=42x+22.The positive correlation (r = 0.74) has an r2 value of 0.55, and a p-value of 0.09.")

QPBMS <- q.cl(labPBMS, d.PBMS, "PBMS_cl") +
  capt("Q-C relationship in the Main Stem of Pheasant Branch Creek (inlet to Lake Mendota). The linear regression is represented by the equation y=-67x+150. The negative correlation (r = -0.34) has an r2 value of 0.12, and a p-value of 0.58.")

QPBSF <- q.cl(labPBSF, d.PBSF, "PBSF_cl") +
  capt("Q-C relationship in the South Fork of Pheasant Branch (high chloride contribution to Lake Mendota). The linear regression is represented by the equation y=-6200x+640. The negative correlation (r = -0.84) has an r2 value of 0.7and a p-value of 0.074.")

```

```{r}
#Linear Regression Figures

YN

SMC

DC

PBMS

PBSF

YI

SW

YS

#Q-C Relationship Figures

QYN

Q6MC

QDC

QPBMS

QPBSF

QYI

```
